package FindTheDifference_389;

/**
 * Given two strings s and t which consist of only lowercase letters.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * <p>
 * Find the letter that was added in t.
 * <p>
 * Example:
 * <p>
 * Input:
 * s = "abcd"
 * t = "abcde"
 * <p>
 * Output:
 * e
 * <p>
 * Explanation:
 * 'e' is the letter that was added.
 */
class Solution {
    public char findTheDifference(String s, String t) {
        char c = t.charAt(t.length() - 1);
        for (int i = 0; i < s.length(); i++) {
            c ^= s.charAt(i);
            c ^= t.charAt(i);
        }
        return c;
    }

    public char findTheDifference2(String s, String t) {
        char[] first = s.toCharArray();
        char[] second = t.toCharArray();
        int res = 0;
        for (int i = 0; i < first.length; i++) {
            res += second[i];
            res -= first[i];
        }
        res += second[second.length - 1];
        return (char) res;
    }
}
